# Site settings
title: Engineering researches and stories
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is an attempt to provide insight to the society as a part of the
  responsibility given to paytm's engineers. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://paytm.com" # the base hostname & protocol for your site
twitter_username: paytm
github_username:  paytm

# Build settings
markdown: kramdown
